op {
  graph_op_name: "OrcRowReader"
  visibility: SKIP
  out_arg {
    name: "reader_handle"
    description: <<END
The handle to reference the Reader.
END
  }
  attr {
    name: "compression_type"
    description: <<END
Compression type of orc file ,the type must be snappy, lz4 or none.
END
  }
  attr {
    name: "container"
    description: <<END
If non-empty, this reader is placed in the given container.
Otherwise, a default container is used.
END
  }
  attr {
    name: "shared_name"
    description: <<END
If non-empty, this reader is named in the given bucket
with this shared_name. Otherwise, the node name is used instead.
END
  }
  summary: "A Reader that outputs the lines of a file delimited by \'\\n\'."
}
